"""empty message

Revision ID: dfe45d936479
Revises: 
Create Date: 2022-05-15 19:00:16.317631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe45d936479'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('category_name', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('category_name'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('companies',
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('company_name')
    )
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('date_of_registration', sa.Date(), nullable=True),
    sa.Column('cart', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('articleUrl', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.category_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('img2', sa.Text(), nullable=True),
    sa.Column('img3', sa.Text(), nullable=True),
    sa.Column('sale', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('cart_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.category_name'], ),
    sa.ForeignKeyConstraint(['company'], ['companies.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=True)
    op.create_table('slideshow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_name'], ['companies.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slideshow')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_table('products')
    op.drop_table('articles')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('categories')
    op.drop_table('cart')
    # ### end Alembic commands ###
